//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograf
    {
        public int FotoID { get; set; }
        public string FotoBaslik { get; set; }
        public string FotoAciklama { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public System.DateTime SonGuncelleme { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
