//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoKategori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FotoKategori()
        {
            this.Fotograf = new HashSet<Fotograf>();
        }
    
        public int FotoKategoriID { get; set; }
        public string Data { get; set; }
        public string FotoClass { get; set; }
        public string FotoKatAdi { get; set; }
        public string FotoKatAciklama { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public System.Guid UserID { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotograf> Fotograf { get; set; }
    }
}
