//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminer
    {
        public int SeminerID { get; set; }
        public string SeminerBaslik { get; set; }
        public string Adres { get; set; }
        public System.DateTime Zaman { get; set; }
        public string SeminerAciklama { get; set; }
        public int UserID { get; set; }
    }
}
